### ISSUE TITLE
Pennsylvania PCRE

### ISSUE THREAD

**Issue by skwerlman** [statedecoded/law-identifier#1]
Hi,

I'd like to improve the PCRE for Pennsylvania, but I'm not certain how much of each court ruling section title it should capture.

I have two versions ATM, one which captures the entire title, and one which makes two separate captures, one before and after the comma.

If either of these is actually an improvement, feel free to use them.

Capture the entire title:

```
((\d{1,2}\sPa?\.(C\.)?S\.(A\.)?\s)?(§|Rule|Section)\s?\d{1,4}\(?[a-z]?\)?(\.\d{1,3}[a-z]?)?(\sof\sthe\s[A-Za-z “”’()]+)?(, )?){1,2}
```

Capture before and after the `,`

```
(\d{1,2}\sPa?\.(C\.)?S\.(A\.)?\s)?(§|Rule|Section)\s?\d{1,4}\(?[a-z]?\)?(\.\d{1,3}[a-z]?)?(\sof\sthe\s[A-Za-z “”’()]+)?
```

**Comment by waldoj** [comment]
I'm not sure how much of each court ruling section title it should capture, either! The State Decoded is only concerned with cross-references within the code, but it seemed foolish not to try to create regexes that would be effective for citations within court rulings, too. I've incorporated the first one into [the PA regex](https://github.com/statedecoded/law-identifier/blob/master/Pennsylvania.md), which will no doubt be of help to folks. Thank you!

**Comment by skwerlman** [comment]
No problem!

Might want to update the note about it stumbling on "Section 314(a) of the Workers’ Compensation Act (“Act”), 77 P.S. § 651(a)", since it matches that perfectly :smile:

**Comment by waldoj** [comment]
D'oh! Thanks. :) I've got the flu right now, and my brain's not working so well. I appreciate it!
